name: Swagger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Swagger Codegen CLI
        uses: CapsLock-Studio/swagger-codegen-action@v1
        with:
          action: generate
          input: swagger.yaml
          language: swagger-yaml
      - name: Upload swagger.json
        uses: actions/upload-artifact@v2
        with:
          name: spec-file
          path: swagger.json
  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download swagger.json
        uses: actions/download-artifact@v2
        with:
          name: spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

